spring.application.name=DiscoverEurope
spring.jackson.default-property-inclusion=non_null

# MONGODB CONFIGURATION
spring.mongodb.uri=mongodb://localhost:27018,localhost:27019,localhost:27020/DiscoverEurope?replicaSet=rs0&w=1&readPreference=secondaryPreferred
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# NEO4J CONFIGURATION
spring.neo4j.uri=bolt://localhost:7687
spring.data.neo4j.database=neo4j
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=Prova2001
logging.level.org.springframework.data.neo4j.cypher=DEBUG

